package com.raiec.ai.web.dto;

/**
 * Officer-facing AI assessment.
 * @param source "llm" when generated by a model, "rule-based" when synthesised locally.
 * @param riskLevel HIGH | MEDIUM | LOW.
 */
public record AiAssessmentResponse(
        String tenderNo,
        String source,
        String riskLevel,
        String summary,
        String generatedAt
) {
}
